#!/usr/bin/env python3
"""
Live end-to-end edge-case test for the Oracle->Postgres converter hardening.

Creates dictionary-driven fixture tables in the *real* Oracle container that
reproduce the confirmed converter edge cases, runs the *real* migration over
them, then asserts on the *real* Postgres side: column types, DEFAULT clauses
enforced on fresh inserts, CHECK enforcement (accept good / reject bad), and a
composite FK. Row-count equality is necessary but NOT sufficient here.

Run:  docker exec ora2pg-jupyter bash -lc 'cd /home/jovyan/work && python docker/test/run_edgecase_test.py'
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import run_migration_test as R

# Two 67-char column names identical through byte 63 (differ only in the suffix).
# Postgres truncates identifiers to 63 bytes; the converter's _short_ident must
# hash-shorten them to DISTINCT names or CREATE TABLE fails with DuplicateColumn.
_LONG_A = "C" + "A" * 62 + "_ONE"
_LONG_B = "C" + "A" * 62 + "_TWO"

FIXTURES = [
    "EDGE_NUM", "EDGE_CHK", "EDGE_CHARLEN", "EDGE_DFLT",
    "EDGE_PARENT", "EDGE_CHILD", "EDGE_DATA",
    "EDGE_MIXP", "EDGE_MIXC",
    # round 2
    "EDGE_VCOL", "EDGE_ONECOL", "EDGE_NUL", "EDGE_ROWID", "EDGE_CHK2", "EDGE_LONGID",
    # round 3
    "EDGE_IDX", "EDGE_DEFP", "EDGE_DEFC",
]

# A standalone sequence (not a table) — exercises migrate_sequences (G1/G5).
_SEQ_OK = "EDGE_SEQ_OK"

# Oracle DDL (+ seed) for each fixture. Parent before child. Each reproduces a
# confirmed bug that the PRE-fix converter mishandled.
ORACLE_DDL = [
    # A1 negative scale + B1 NUMBER(*,s): pre-fix -> NUMERIC(5,-2) (invalid) / dropped scale
    """CREATE TABLE {S}.EDGE_NUM (
        ID    NUMBER(10) PRIMARY KEY,
        QTY   NUMBER(5,-2),
        PRICE NUMBER(*,2)
    )""",
    "INSERT INTO {S}.EDGE_NUM (ID, QTY, PRICE) VALUES (1, 12300, 1.239)",

    # A3 function-name collision (col LENGTH) + A4 CHECK literal w/ reserved words
    """CREATE TABLE {S}.EDGE_CHK (
        ID     NUMBER(10) PRIMARY KEY,
        LENGTH NUMBER(5),
        NAME   VARCHAR2(50),
        SRC    VARCHAR2(30),
        CONSTRAINT CK_FNCOL CHECK (LENGTH(NAME) > 0),
        CONSTRAINT CK_LITERAL CHECK (SRC IN ('SYSDATE','FROM DUAL','NVL'))
    )""",
    "INSERT INTO {S}.EDGE_CHK (ID, LENGTH, NAME, SRC) VALUES (1, 3, 'abc', 'SYSDATE')",

    # B3 VARCHAR2(n CHAR) length under (possibly) multibyte charset
    """CREATE TABLE {S}.EDGE_CHARLEN (
        ID   NUMBER(10) PRIMARY KEY,
        NAME VARCHAR2(100 CHAR),
        CODE VARCHAR2(10 BYTE)
    )""",
    "INSERT INTO {S}.EDGE_CHARLEN (ID, NAME, CODE) VALUES (1, 'short', 'X')",

    # B2 DEFAULT string literal w/ reserved words: pre-fix -> 'CURRENT_TIMESTAMP'
    """CREATE TABLE {S}.EDGE_DFLT (
        ID   NUMBER(10) PRIMARY KEY,
        SRC  VARCHAR2(30) DEFAULT 'SYSDATE',
        KIND VARCHAR2(30) DEFAULT 'BIRTH DATE'
    )""",
    "INSERT INTO {S}.EDGE_DFLT (ID) VALUES (1)",

    # B4 composite FK (plain NUMBER keys) — regression guard for multi-col FK
    """CREATE TABLE {S}.EDGE_PARENT (
        P1 NUMBER(10),
        P2 NUMBER(10),
        CONSTRAINT PK_EDGE_PARENT PRIMARY KEY (P1, P2)
    )""",
    "INSERT INTO {S}.EDGE_PARENT (P1, P2) VALUES (1, 2)",
    """CREATE TABLE {S}.EDGE_CHILD (
        C_ID NUMBER(10) PRIMARY KEY,
        P1   NUMBER(10),
        P2   NUMBER(10),
        CONSTRAINT FK_EDGE_CHILD FOREIGN KEY (P1, P2)
            REFERENCES {S}.EDGE_PARENT (P1, P2)
    )""",
    "INSERT INTO {S}.EDGE_CHILD (C_ID, P1, P2) VALUES (10, 1, 2)",

    # C9 CLOB special chars + bytea(RAW) + DATE->TIMESTAMP + TSLTZ + unquoted DEFAULT
    """CREATE TABLE {S}.EDGE_DATA (
        ID      NUMBER(10) PRIMARY KEY,
        BODY    CLOB,
        PAYLOAD RAW(16),
        WHEN_TS TIMESTAMP(3),
        WHEN_DT DATE,
        TS_LTZ  TIMESTAMP WITH LOCAL TIME ZONE,
        MADE_ON TIMESTAMP DEFAULT SYSTIMESTAMP
    )""",
    ("INSERT INTO {S}.EDGE_DATA (ID, BODY, PAYLOAD, WHEN_TS, WHEN_DT, TS_LTZ) VALUES "
     "(1, 'line1' || CHR(10) || 'a,b,\"c\"' || CHR(9) || 'end', "
     "HEXTORAW('DEADBEEF'), "
     "TIMESTAMP '2024-03-15 14:30:00.500', "
     "TO_DATE('2024-03-15 08:09:10','YYYY-MM-DD HH24:MI:SS'), "
     "TIMESTAMP '2024-01-15 10:30:00 -05:00')"),

    # B4/B5 MIXED composite FK: parent composite PK where one column is an
    # IDENTITY (coerced to bigint) and the other is plain NUMBER (stays numeric).
    # Exercises align_foreign_key_column_types pairing a bigint parent col and a
    # numeric parent col within the SAME composite FK.
    """CREATE TABLE {S}.EDGE_MIXP (
        P1    NUMBER GENERATED BY DEFAULT AS IDENTITY,
        P2    NUMBER(10),
        LABEL VARCHAR2(20),
        CONSTRAINT PK_EDGE_MIXP PRIMARY KEY (P1, P2)
    )""",
    "INSERT INTO {S}.EDGE_MIXP (P1, P2, LABEL) VALUES (1, 100, 'a')",
    """CREATE TABLE {S}.EDGE_MIXC (
        C_ID NUMBER(10) PRIMARY KEY,
        F1   NUMBER(10),
        F2   NUMBER(10),
        CONSTRAINT FK_EDGE_MIXC FOREIGN KEY (F1, F2)
            REFERENCES {S}.EDGE_MIXP (P1, P2)
    )""",
    "INSERT INTO {S}.EDGE_MIXC (C_ID, F1, F2) VALUES (10, 1, 100)",

    # F1 virtual/generated column: pre-fix emitted DEFAULT <col-ref> -> CREATE crash
    # (table LOST after DROP CASCADE). Now materialised as a plain column (snapshot).
    """CREATE TABLE {S}.EDGE_VCOL (
        FNAME    VARCHAR2(20),
        LNAME    VARCHAR2(20),
        FULLNAME VARCHAR2(40) GENERATED ALWAYS AS (FNAME||LNAME) VIRTUAL
    )""",
    "INSERT INTO {S}.EDGE_VCOL (FNAME, LNAME) VALUES ('Jane', 'Doe')",

    # F2 single-column-table NULL: csv.writer emits lone empty as quoted "" -> pre-fix
    # loaded as '' not NULL. Now FORCE_NULL fixes it.
    """CREATE TABLE {S}.EDGE_ONECOL (V VARCHAR2(10))""",
    "INSERT INTO {S}.EDGE_ONECOL (V) VALUES (NULL)",
    "INSERT INTO {S}.EDGE_ONECOL (V) VALUES ('x')",

    # F3 NUL byte (CHR(0)) in text: pre-fix aborted the whole-table COPY. Now stripped.
    """CREATE TABLE {S}.EDGE_NUL (ID NUMBER(5) PRIMARY KEY, TXT VARCHAR2(50))""",
    "INSERT INTO {S}.EDGE_NUL (ID, TXT) VALUES (1, 'ab'||CHR(0)||'cd')",

    # F4 ROWID column: pre-fix emitted `RID ROWID` -> type does not exist -> crash.
    """CREATE TABLE {S}.EDGE_ROWID (ID NUMBER(5) PRIMARY KEY, RID ROWID)""",
    "INSERT INTO {S}.EDGE_ROWID (ID) VALUES (1)",

    # F5 CHECK w/ Oracle-only fns: INSTR (now -> strpos) + NVL2 (unconvertible). Pre-fix
    # a failing CHECK rolled back the PK too; now per-statement isolation keeps the PK.
    """CREATE TABLE {S}.EDGE_CHK2 (
        ID   NUMBER(5) PRIMARY KEY,
        CODE VARCHAR2(10),
        CONSTRAINT CK_INSTR CHECK (INSTR(CODE,'X') > 0),
        CONSTRAINT CK_NVL2  CHECK (NVL2(CODE, 1, 0) = 1)
    )""",
    "INSERT INTO {S}.EDGE_CHK2 (ID, CODE) VALUES (1, 'AXB')",

    # F6 identifiers > 63 bytes (two cols identical through byte 63): pre-fix Postgres
    # truncates both to the same 63 chars -> DuplicateColumn. Now _short_ident hashes.
    f'CREATE TABLE {{S}}.EDGE_LONGID ( '
    f'ID NUMBER(5) PRIMARY KEY, "{_LONG_A}" NUMBER(5), "{_LONG_B}" NUMBER(5) )',
    f'INSERT INTO {{S}}.EDGE_LONGID (ID, "{_LONG_A}", "{_LONG_B}") VALUES (1, 10, 20)',

    # G2/G3 DESCENDING + FUNCTION-BASED indexes (Oracle stores both as
    # FUNCTION-BASED NORMAL): pre-fix the index_type='NORMAL' filter dropped them
    # entirely. EDGE_IDX_PLAIN is the regression guard (plain ascending NORMAL).
    """CREATE TABLE {S}.EDGE_IDX (
        ID   NUMBER(10) PRIMARY KEY,
        NAME VARCHAR2(50),
        TS   NUMBER(10)
    )""",
    "CREATE INDEX EDGE_IDX_DESC  ON {S}.EDGE_IDX (TS DESC)",
    "CREATE INDEX EDGE_IDX_FUNC  ON {S}.EDGE_IDX (UPPER(NAME))",
    "CREATE INDEX EDGE_IDX_PLAIN ON {S}.EDGE_IDX (NAME)",
    "INSERT INTO {S}.EDGE_IDX (ID, NAME, TS) VALUES (1, 'abc', 100)",

    # G4 DEFERRABLE INITIALLY DEFERRED FK: pre-fix lost its deferrability.
    """CREATE TABLE {S}.EDGE_DEFP (ID NUMBER(10) PRIMARY KEY)""",
    "INSERT INTO {S}.EDGE_DEFP (ID) VALUES (1)",
    """CREATE TABLE {S}.EDGE_DEFC (
        C_ID NUMBER(10) PRIMARY KEY,
        P_ID NUMBER(10),
        CONSTRAINT FK_EDGE_DEFER FOREIGN KEY (P_ID)
            REFERENCES {S}.EDGE_DEFP (ID) DEFERRABLE INITIALLY DEFERRED
    )""",
    "INSERT INTO {S}.EDGE_DEFC (C_ID, P_ID) VALUES (10, 1)",
]

DROP_ORDER = ["EDGE_CHILD", "EDGE_PARENT", "EDGE_NUM", "EDGE_CHK",
              "EDGE_CHARLEN", "EDGE_DFLT", "EDGE_DATA",
              "EDGE_MIXC", "EDGE_MIXP",
              "EDGE_VCOL", "EDGE_ONECOL", "EDGE_NUL", "EDGE_ROWID",
              "EDGE_CHK2", "EDGE_LONGID",
              "EDGE_IDX", "EDGE_DEFC", "EDGE_DEFP"]


def _drop_all(ora, schema):
    cur = ora.cursor()
    for t in DROP_ORDER:
        try:
            cur.execute(f'DROP TABLE "{schema}"."{t}" CASCADE CONSTRAINTS')
        except Exception:
            pass
    try:
        cur.execute(f'DROP SEQUENCE "{schema}"."{_SEQ_OK}"')
    except Exception:
        pass
    cur.close()


def setup_oracle(ns):
    schema = ns["ORACLE_SCHEMA"]
    ora = ns["get_oracle_connection"]()
    try:
        _drop_all(ora, schema)
        cur = ora.cursor()
        for stmt in ORACLE_DDL:
            cur.execute(stmt.format(S=schema))
        # A normal standalone sequence migrate_sequences must (re)create.
        cur.execute(f'CREATE SEQUENCE "{schema}"."{_SEQ_OK}" '
                    f'START WITH 42 INCREMENT BY 1 MAXVALUE 100000')
        ora.commit()
        cur.close()
        # Report the charset so we know if the CHAR-length bug is even active here.
        cur = ora.cursor()
        cur.execute("SELECT value FROM nls_database_parameters "
                    "WHERE parameter = 'NLS_CHARACTERSET'")
        cs = cur.fetchone()[0]
        cur.execute("SELECT char_length, data_length FROM all_tab_columns "
                    "WHERE owner=:o AND table_name='EDGE_CHARLEN' AND column_name='NAME'",
                    o=schema)
        cl, dl = cur.fetchone()
        cur.close()
        print(f"Oracle NLS_CHARACTERSET={cs}; EDGE_CHARLEN.NAME char_length={cl} "
              f"data_length={dl} (multibyte bug active if data_length>char_length)")
    finally:
        ora.close()


# ---- assertions on the Postgres side ----
PASS, FAIL = [], []


def check(name, ok, detail=""):
    (PASS if ok else FAIL).append(name)
    print(f"  [{'PASS' if ok else 'FAIL'}] {name}" + (f" — {detail}" if detail else ""))


def verify_postgres(ns):
    sch = ns["PG_SCHEMA"]
    pg = ns["get_postgres_connection"]()
    pg.autocommit = False
    cur = pg.cursor()

    def col(table, column):
        # Columns are created quoted-UPPER-case, so information_schema stores
        # them upper-case; query with the upper-case name.
        cur.execute(
            "SELECT data_type, numeric_precision, numeric_scale, "
            "character_maximum_length, column_default "
            "FROM information_schema.columns "
            "WHERE table_schema=%s AND table_name=%s AND column_name=%s",
            (sch, table, column.upper()))
        return cur.fetchone()

    print("\n--- A1/B1: NUMBER scale edge cases (EDGE_NUM) ---")
    qty = col("EDGE_NUM", "qty")
    check("EDGE_NUM table migrated (qty present)", qty is not None, str(qty))
    if qty:
        # negative scale must NOT survive; valid numeric (scale 0 -> reported 0 or None)
        check("QTY is numeric with non-negative scale",
              qty[0] == "numeric" and (qty[2] is None or qty[2] >= 0), str(qty))
    price = col("EDGE_NUM", "price")
    if price:
        check("PRICE NUMBER(*,2) -> numeric(38,2)",
              price[0] == "numeric" and price[1] == 38 and price[2] == 2, str(price))
    # data integrity: the migrated row exists, price rounded to scale 2 by PG
    cur.execute(f'SELECT "PRICE" FROM "{sch}"."EDGE_NUM" WHERE "ID"=1')
    pr = cur.fetchone()
    check("PRICE stored at scale 2 (1.24)", pr is not None and str(pr[0]) == "1.24", str(pr))

    print("\n--- A3/A4: CHECK constraints (EDGE_CHK) ---")
    # CK_LITERAL accepts 'SYSDATE'/'FROM DUAL'/'NVL', rejects others
    for i, (val, should_ok) in enumerate([("SYSDATE", True), ("FROM DUAL", True),
                                          ("NVL", True), ("OTHER", False)]):
        try:
            cur.execute(f'INSERT INTO "{sch}"."EDGE_CHK"("ID","LENGTH","NAME","SRC") '
                        f'VALUES (%s, 1, %s, %s)', (901 + i, 'x', val))
            pg.commit()
            ok = should_ok
            detail = f"accepted {val!r}"
        except Exception:
            pg.rollback()
            ok = not should_ok
            detail = f"rejected {val!r}"
        check(f"CK_LITERAL {'accepts' if should_ok else 'rejects'} {val!r}", ok, detail)
    # CK_FNCOL: LENGTH(NAME)>0 must reject empty name
    try:
        cur.execute(f'INSERT INTO "{sch}"."EDGE_CHK"("ID","LENGTH","NAME","SRC") '
                    f"VALUES (950, 1, '', 'NVL')")
        pg.commit()
        check("CK_FNCOL rejects empty NAME", False, "empty NAME was accepted")
    except Exception:
        pg.rollback()
        check("CK_FNCOL rejects empty NAME", True, "rejected as expected")

    print("\n--- B3: VARCHAR2(n CHAR) length (EDGE_CHARLEN) ---")
    name = col("EDGE_CHARLEN", "name")
    code = col("EDGE_CHARLEN", "code")
    if name:
        check("NAME VARCHAR2(100 CHAR) -> varchar(100)",
              name[3] == 100, f"character_maximum_length={name[3]}")
    if code:
        check("CODE VARCHAR2(10 BYTE) -> varchar(10)",
              code[3] == 10, f"character_maximum_length={code[3]}")

    print("\n--- B2: DEFAULT literal preserved (EDGE_DFLT) ---")
    src = col("EDGE_DFLT", "src")
    kind = col("EDGE_DFLT", "kind")
    if src:
        check("SRC default is literal 'SYSDATE' (not CURRENT_TIMESTAMP)",
              src[4] is not None and "SYSDATE" in src[4] and "CURRENT_TIMESTAMP" not in src[4],
              f"column_default={src[4]!r}")
    if kind:
        check("KIND default is literal 'BIRTH DATE' (not BIRTH TIMESTAMP)",
              kind[4] is not None and "BIRTH DATE" in kind[4],
              f"column_default={kind[4]!r}")
    # prove the default is actually applied on a fresh insert
    cur.execute(f'INSERT INTO "{sch}"."EDGE_DFLT"("ID") VALUES (2)')
    pg.commit()
    cur.execute(f'SELECT "SRC","KIND" FROM "{sch}"."EDGE_DFLT" WHERE "ID"=2')
    fresh = cur.fetchone()
    check("fresh INSERT applies literal defaults",
          fresh == ("SYSDATE", "BIRTH DATE"), str(fresh))

    print("\n--- B4: composite FK enforced (EDGE_CHILD -> EDGE_PARENT) ---")
    cur.execute(
        "SELECT count(*) FROM information_schema.table_constraints "
        "WHERE table_schema=%s AND table_name='EDGE_CHILD' "
        "AND constraint_type='FOREIGN KEY'", (sch,))
    fkn = cur.fetchone()[0]
    check("composite FK exists on EDGE_CHILD", fkn >= 1, f"{fkn} FK(s)")
    try:
        cur.execute(f'INSERT INTO "{sch}"."EDGE_CHILD"("C_ID","P1","P2") VALUES (99, 7, 7)')
        pg.commit()
        check("composite FK rejects orphan (7,7)", False, "orphan accepted")
    except Exception:
        pg.rollback()
        check("composite FK rejects orphan (7,7)", True, "rejected as expected")

    print("\n--- C9/C7: data fidelity round-trip (EDGE_DATA) ---")
    cur.execute(
        f'SELECT "BODY","PAYLOAD","WHEN_TS","WHEN_DT" '
        f'FROM "{sch}"."EDGE_DATA" WHERE "ID"=1')
    body, payload, when_ts, when_dt = cur.fetchone()
    expected_body = 'line1\na,b,"c"\tend'
    check("CLOB round-trips newline/comma/quote/tab exactly",
          body == expected_body, repr(body))
    check("RAW->bytea round-trips (DEADBEEF)",
          bytes(payload) == bytes.fromhex("DEADBEEF"), repr(bytes(payload)))
    check("TIMESTAMP(3) value preserved (2024-03-15 14:30:00.5)",
          str(when_ts) == "2024-03-15 14:30:00.500000", str(when_ts))
    # DATE -> TIMESTAMP must keep the time component, not truncate to midnight
    check("DATE->TIMESTAMP keeps time component (08:09:10)",
          str(when_dt) == "2024-03-15 08:09:10", str(when_dt))
    # types
    wdt = col("EDGE_DATA", "when_dt")
    check("WHEN_DT is timestamp (DATE mapped to TIMESTAMP)",
          wdt and wdt[0].startswith("timestamp"), str(wdt))
    tsl = col("EDGE_DATA", "ts_ltz")
    check("TS_LTZ is timestamp with time zone",
          tsl and tsl[0] == "timestamp with time zone", str(tsl))
    body_col = col("EDGE_DATA", "body")
    check("BODY CLOB -> text", body_col and body_col[0] == "text", str(body_col))
    pay_col = col("EDGE_DATA", "payload")
    check("PAYLOAD RAW -> bytea", pay_col and pay_col[0] == "bytea", str(pay_col))
    # TS_LTZ instant preserved: -05:00 10:30 == 15:30 UTC
    cur.execute(f"SET TIME ZONE 'UTC'")
    cur.execute(f"SELECT to_char(\"TS_LTZ\" AT TIME ZONE 'UTC','YYYY-MM-DD HH24:MI:SS') "
                f'FROM "{sch}"."EDGE_DATA" WHERE "ID"=1')
    tsl_utc = cur.fetchone()[0]
    check("TS_LTZ instant preserved (2024-01-15 15:30:00 UTC)",
          tsl_utc == "2024-01-15 15:30:00", tsl_utc)
    # unquoted DEFAULT SYSTIMESTAMP -> CURRENT_TIMESTAMP (a real function default)
    mo = col("EDGE_DATA", "made_on")
    check("MADE_ON default converted to CURRENT_TIMESTAMP",
          mo and mo[4] and "CURRENT_TIMESTAMP" in mo[4].upper(), str(mo and mo[4]))
    cur.execute(f'INSERT INTO "{sch}"."EDGE_DATA"("ID","PAYLOAD") VALUES (2, %s)',
                (b"\x01\x02",))
    pg.commit()
    cur.execute(f'SELECT "MADE_ON" FROM "{sch}"."EDGE_DATA" WHERE "ID"=2')
    made_on = cur.fetchone()[0]
    check("MADE_ON default populates on fresh insert", made_on is not None, str(made_on))

    print("\n--- B4/B5: MIXED composite FK (identity + NUMBER parent cols) ---")
    p1 = col("EDGE_MIXP", "p1")
    p2 = col("EDGE_MIXP", "p2")
    check("parent P1 (identity) -> bigint", p1 and p1[0] == "bigint", str(p1))
    check("parent P2 (plain NUMBER) -> numeric", p2 and p2[0] == "numeric", str(p2))
    f1 = col("EDGE_MIXC", "f1")
    f2 = col("EDGE_MIXC", "f2")
    # the bigint pair must have been aligned; the numeric pair left numeric
    check("child F1 aligned to parent bigint",
          f1 and f1[0] == "bigint", str(f1))
    check("child F2 stays numeric (matches parent)",
          f2 and f2[0] == "numeric", str(f2))
    cur.execute(
        "SELECT count(*) FROM information_schema.table_constraints "
        "WHERE table_schema=%s AND table_name='EDGE_MIXC' "
        "AND constraint_type='FOREIGN KEY'", (sch,))
    check("mixed composite FK exists on EDGE_MIXC", cur.fetchone()[0] >= 1)
    # enforcement: valid ref accepted, orphan rejected
    try:
        cur.execute(f'INSERT INTO "{sch}"."EDGE_MIXC"("C_ID","F1","F2") VALUES (11, 1, 100)')
        pg.commit()
        check("mixed composite FK accepts valid (1,100)", True, "accepted")
    except Exception as e:
        pg.rollback()
        check("mixed composite FK accepts valid (1,100)", False, str(e))
    try:
        cur.execute(f'INSERT INTO "{sch}"."EDGE_MIXC"("C_ID","F1","F2") VALUES (12, 1, 999)')
        pg.commit()
        check("mixed composite FK rejects orphan (1,999)", False, "orphan accepted")
    except Exception:
        pg.rollback()
        check("mixed composite FK rejects orphan (1,999)", True, "rejected as expected")
    # the parent identity column is still a working identity after coercion
    cur.execute(
        "SELECT is_identity FROM information_schema.columns "
        "WHERE table_schema=%s AND table_name='EDGE_MIXP' AND column_name='P1'", (sch,))
    isid = cur.fetchone()
    check("parent P1 remains an IDENTITY after bigint coercion",
          isid and isid[0] == "YES", str(isid))

    print("\n--- F1: virtual/generated column materialized (EDGE_VCOL) ---")
    cur.execute("SELECT to_regclass(%s)", (f'\"{sch}\".\"EDGE_VCOL\"',))
    check("EDGE_VCOL table exists (not lost to DEFAULT col-ref crash)",
          cur.fetchone()[0] is not None)
    cur.execute(f'SELECT "FULLNAME" FROM "{sch}"."EDGE_VCOL" WHERE "FNAME"=%s', ("Jane",))
    row = cur.fetchone()
    check("virtual column holds Oracle-computed snapshot ('JaneDoe')",
          row and row[0] == "JaneDoe", str(row))
    cur.execute("SELECT is_generated FROM information_schema.columns "
                "WHERE table_schema=%s AND table_name='EDGE_VCOL' AND column_name='FULLNAME'",
                (sch,))
    g = cur.fetchone()
    check("virtual column materialized as PLAIN (is_generated=NEVER)",
          g and g[0] == "NEVER", str(g))

    print("\n--- F2: single-column NULL stays NULL (EDGE_ONECOL) ---")
    cur.execute(f'SELECT count(*) FROM "{sch}"."EDGE_ONECOL"')
    check("both rows loaded", cur.fetchone()[0] == 2)
    cur.execute(f'SELECT count(*) FROM "{sch}"."EDGE_ONECOL" WHERE "V" IS NULL')
    n = cur.fetchone()[0]
    check("the NULL row is NULL, not '' (FORCE_NULL)", n == 1, f"IS NULL count={n}")

    print("\n--- F3: NUL byte stripped, table loads (EDGE_NUL) ---")
    cur.execute(f'SELECT count(*) FROM "{sch}"."EDGE_NUL"')
    check("EDGE_NUL row loaded (COPY not aborted by 0x00)", cur.fetchone()[0] == 1)
    cur.execute(f'SELECT "TXT" FROM "{sch}"."EDGE_NUL" WHERE "ID"=1')
    t = cur.fetchone()
    check("NUL byte stripped ('ab\\x00cd' -> 'abcd')", t and t[0] == "abcd", str(t))

    print("\n--- F4: ROWID column mapped to text (EDGE_ROWID) ---")
    cur.execute("SELECT to_regclass(%s)", (f'\"{sch}\".\"EDGE_ROWID\"',))
    check("EDGE_ROWID table exists (ROWID not emitted verbatim)",
          cur.fetchone()[0] is not None)
    rid = col("EDGE_ROWID", "rid")
    check("RID column is text/varchar",
          rid and rid[0] in ("text", "character varying"), str(rid))

    print("\n--- F5: bad CHECK isolated, PK + INSTR check survive (EDGE_CHK2) ---")
    cur.execute("SELECT count(*) FROM information_schema.table_constraints "
                "WHERE table_schema=%s AND table_name='EDGE_CHK2' "
                "AND constraint_type='PRIMARY KEY'", (sch,))
    check("PK survived despite an unconvertible CHECK in the batch",
          cur.fetchone()[0] == 1)
    cur.execute("SELECT count(*) FROM information_schema.check_constraints cc "
                "JOIN information_schema.constraint_column_usage ccu "
                "  ON cc.constraint_name=ccu.constraint_name "
                "  AND cc.constraint_schema=ccu.constraint_schema "
                "WHERE ccu.table_schema=%s AND ccu.table_name='EDGE_CHK2' "
                "AND cc.constraint_name='CK_INSTR'", (sch,))
    check("INSTR CHECK present (converted to strpos)", cur.fetchone()[0] >= 1)
    # CK_INSTR enforces: a CODE without 'X' must be rejected
    try:
        cur.execute(f'INSERT INTO "{sch}"."EDGE_CHK2"("ID","CODE") VALUES (2, %s)', ("ABC",))
        pg.commit()
        check("INSTR CHECK enforces (rejects CODE without X)", False, "accepted ABC")
    except Exception:
        pg.rollback()
        check("INSTR CHECK enforces (rejects CODE without X)", True, "rejected")
    cur.execute("SELECT count(*) FROM information_schema.check_constraints "
                "WHERE constraint_schema=%s AND constraint_name='CK_NVL2'", (sch,))
    check("unconvertible NVL2 CHECK was dropped (isolated, not fatal)",
          cur.fetchone()[0] == 0)

    print("\n--- F6: >63-byte identifiers hash-shortened distinctly (EDGE_LONGID) ---")
    cur.execute("SELECT to_regclass(%s)", (f'\"{sch}\".\"EDGE_LONGID\"',))
    check("EDGE_LONGID table exists (no DuplicateColumn truncation collision)",
          cur.fetchone()[0] is not None)
    cur.execute("SELECT column_name FROM information_schema.columns "
                "WHERE table_schema=%s AND table_name='EDGE_LONGID'", (sch,))
    names = [r[0] for r in cur.fetchall()]
    check("all 3 columns present with distinct <=63-byte names",
          len(names) == 3 and len(set(names)) == 3 and all(len(x.encode()) <= 63 for x in names),
          str(names))
    cur.execute(f'SELECT count(*) FROM "{sch}"."EDGE_LONGID"')
    check("EDGE_LONGID row loaded under shortened names", cur.fetchone()[0] == 1)

    print("\n--- G2/G3: DESC + function-based indexes recovered (EDGE_IDX) ---")
    cur.execute("SELECT indexname, indexdef FROM pg_indexes "
                "WHERE schemaname=%s AND tablename='EDGE_IDX'", (sch,))
    idx = {n: d for n, d in cur.fetchall()}
    check("DESC index EDGE_IDX_DESC created with DESC ordering",
          "EDGE_IDX_DESC" in idx and "DESC" in idx["EDGE_IDX_DESC"].upper(),
          idx.get("EDGE_IDX_DESC"))
    check("function-based index EDGE_IDX_FUNC created with upper()",
          "EDGE_IDX_FUNC" in idx and "upper" in idx["EDGE_IDX_FUNC"].lower(),
          idx.get("EDGE_IDX_FUNC"))
    check("plain index EDGE_IDX_PLAIN still created (regression guard)",
          "EDGE_IDX_PLAIN" in idx, idx.get("EDGE_IDX_PLAIN"))

    print("\n--- G4: FK keeps DEFERRABLE INITIALLY DEFERRED (EDGE_DEFC) ---")
    cur.execute("SELECT condeferrable, condeferred FROM pg_constraint "
                "WHERE conname='FK_EDGE_DEFER'")
    dfr = cur.fetchone()
    check("FK_EDGE_DEFER is DEFERRABLE INITIALLY DEFERRED",
          dfr == (True, True), str(dfr))
    # functional proof: a deferred FK lets us insert child-before-parent in one txn
    try:
        cur.execute("SET CONSTRAINTS ALL DEFERRED")
        cur.execute(f'INSERT INTO "{sch}"."EDGE_DEFC"("C_ID","P_ID") VALUES (20, 99)')
        cur.execute(f'INSERT INTO "{sch}"."EDGE_DEFP"("ID") VALUES (99)')
        pg.commit()
        check("deferred FK allows child-before-parent within a txn", True, "committed")
    except Exception as e:
        pg.rollback()
        check("deferred FK allows child-before-parent within a txn", False, str(e))

    print("\n--- G1/G5: sequences isolated + ISEQ$$ junk filtered ---")
    cur.execute("SELECT count(*) FROM pg_sequences WHERE schemaname=%s "
                "AND sequencename=%s", (sch, _SEQ_OK))
    check("standalone sequence EDGE_SEQ_OK migrated", cur.fetchone()[0] == 1)
    cur.execute("SELECT count(*) FROM pg_sequences WHERE schemaname=%s "
                "AND sequencename LIKE 'ISEQ$$%%'", (sch,))
    n_iseq = cur.fetchone()[0]
    check("no Oracle ISEQ$$ backing sequences migrated as junk",
          n_iseq == 0, f"ISEQ$$ count={n_iseq}")
    # native identity sequence for the identity table should still exist
    cur.execute("SELECT count(*) FROM pg_sequences WHERE schemaname=%s "
                "AND sequencename LIKE 'EDGE_MIXP%%'", (sch,))
    check("native identity sequence still present for EDGE_MIXP",
          cur.fetchone()[0] >= 1)

    cur.close()
    pg.close()


def main():
    overrides = R.build_overrides()
    overrides["TABLE_NAMES"] = list(FIXTURES)
    overrides["DISCOVER_TABLES"] = False
    overrides["RESPECT_LOAD_ORDER"] = True
    # Deliberately migrate into a schema whose name is NOT a bare-legal SQL
    # identifier (the dash). This reproduces the production incident where every
    # table failed with `SET search_path TO acs-migration` -> 'syntax error at
    # or near "-"'. Forced (not env-derived) so the `_pg_search_path` quoting (and
    # every `_pg_qualified` reference) is exercised end-to-end on EVERY run — a
    # regression can never slip through silently. The container ships PG_SCHEMA=public
    # in its env, which is exactly why we must not read it here.
    overrides["PG_SCHEMA"] = "acs-migration"
    ns = R.load_notebook_namespace(overrides)

    # The migration assumes its target schema already exists (it never issues
    # CREATE SCHEMA). Create it up front, quoted, exactly as the real operator
    # would have done for "acs-migration".
    sch = ns["PG_SCHEMA"]
    pg = ns["get_postgres_connection"]()
    pg.autocommit = True
    pg.cursor().execute(f'CREATE SCHEMA IF NOT EXISTS {ns["_pg_ident"](sch)}')
    pg.close()
    print(f"=== Target schema: {sch!r} (quoted as {ns['_pg_ident'](sch)}) ===")

    print("=== Setting up Oracle fixtures ===")
    setup_oracle(ns)

    # Pre-clean Postgres of junk sequences left by PRIOR (pre-fix) runs so the
    # "no ISEQ$$ sequences created" assertion (G5) reflects THIS run only.
    pg = ns["get_postgres_connection"]()
    pgc = pg.cursor()
    pgc.execute("SELECT sequencename FROM pg_sequences WHERE schemaname=%s "
                "AND (sequencename LIKE 'ISEQ$$%%' OR sequencename=%s)",
                (ns["PG_SCHEMA"], _SEQ_OK))
    for (sname,) in pgc.fetchall():
        pgc.execute(f'DROP SEQUENCE IF EXISTS "{ns["PG_SCHEMA"]}"."{sname}" CASCADE')
    pg.commit()
    pgc.close()
    pg.close()

    print("\n=== Running real migration over fixtures ===")
    ns["migrate_all_tables"]()

    print("\n=== Verifying Postgres side ===")
    verify_postgres(ns)

    print("\n" + "=" * 52)
    print(f"EDGE-CASE RESULT: {len(PASS)} passed, {len(FAIL)} failed")
    if FAIL:
        print("FAILURES: " + ", ".join(FAIL))
        sys.exit(1)
    print("ALL EDGE-CASE ASSERTIONS PASSED")


if __name__ == "__main__":
    main()
