-- ---------------------------------------------------------------------------
-- Test schema for the Oracle -> Postgres migration notebook.
--
-- Objects are created FULLY QUALIFIED under the ORACLE_USER schema so this
-- works regardless of which privileged user the init runner connects as.
-- ORACLE_USER (== APP_USER "oracle_user") is created by the image before this
-- script runs.
--
-- This intentionally exercises the notebook's full feature set:
--   * data types: VARCHAR2, NUMBER(p,s), NUMBER(1), DATE, TIMESTAMP, CLOB
--   * IDENTITY column          -> tests migrate_identity_columns
--   * standalone SEQUENCE       -> tests migrate_sequences
--   * PRIMARY KEY / UNIQUE / CHECK constraints + INDEX -> tests 2nd pass
--   * FOREIGN KEY (ORDERS -> CUSTOMERS)                 -> tests FK pass + load ordering
--
-- gvenzl runs every init script as `sqlplus -s / as sysdba`, which connects to
-- CDB$ROOT. The APP_USER lives in the XEPDB1 PDB, so we MUST switch containers
-- first or every qualified reference fails with ORA-01918 (user does not exist).
-- ---------------------------------------------------------------------------

ALTER SESSION SET CONTAINER = XEPDB1;

-- Parent table: identity PK, unique email, check constraint, CLOB, timestamp.
CREATE TABLE ORACLE_USER.CUSTOMERS (
    CUSTOMER_ID  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    NAME         VARCHAR2(100) NOT NULL,
    EMAIL        VARCHAR2(200),
    BALANCE      NUMBER(12,2) DEFAULT 0,
    ACTIVE       NUMBER(1)    DEFAULT 1,
    NOTES        CLOB,
    CREATED_AT   TIMESTAMP    DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_CUSTOMERS        PRIMARY KEY (CUSTOMER_ID),
    CONSTRAINT UQ_CUSTOMERS_EMAIL  UNIQUE (EMAIL),
    CONSTRAINT CK_CUSTOMERS_ACTIVE CHECK (ACTIVE IN (0, 1))
);

-- Standalone sequence used to populate ORDERS.ORDER_ID.
CREATE SEQUENCE ORACLE_USER.ORDER_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE;

-- Child table: FK to CUSTOMERS, plain PK, a DATE column, an index on the FK.
CREATE TABLE ORACLE_USER.ORDERS (
    ORDER_ID     NUMBER        NOT NULL,
    CUSTOMER_ID  NUMBER        NOT NULL,
    ORDER_DATE   DATE          DEFAULT SYSDATE,
    AMOUNT       NUMBER(10,2)  NOT NULL,
    STATUS       VARCHAR2(20)  DEFAULT 'NEW',
    CONSTRAINT PK_ORDERS          PRIMARY KEY (ORDER_ID),
    CONSTRAINT FK_ORDERS_CUSTOMER FOREIGN KEY (CUSTOMER_ID)
        REFERENCES ORACLE_USER.CUSTOMERS (CUSTOMER_ID)
);

CREATE INDEX ORACLE_USER.IX_ORDERS_CUSTOMER ON ORACLE_USER.ORDERS (CUSTOMER_ID);
